"""india_cfs_basis.py -- the ONE declared design basis of an India CFS job (WP3.1, decisions D3 / D5).

Two labelled families live in cfg['load_plan'] and never mix:

  1. CFS members (studs, tracks, joists, purlins, girts, all-CFS portal members) -- IS 801:1975 WORKING STRESS:
       design_basis = "IS801_WSM"
       F = 0.60 Fy (IS 801 6.1, PDF p.11); loads = IS 875 (Part 5):1987 cl. 8.1 combinations at factor 1.0:
       DL; DL+IL; DL+WL; DL+EL; DL+IL+WL; DL+IL+EL; (snow replaces IL, Note 1); 0.9DL +- WL/EL for uplift /
       overturning / sliding (Notes 4, 5).  The allowable stresses are increased by 33 1/3 % ONLY for the
       combinations containing WL or EL (IS 801 6.1.2.1 / 6.1.2.2, PDF p.13), with the effective widths for those
       combinations at 0.75 x the stress (5.2.1.1 note, PDF p.6), and the section not less than that required for
       DL + IL (6.1.2.2).  IS 875-2 3.2.1 imposed-load reductions apply to IL only and never with EL (IS 875-5 Note 3).
       -> load_plan['cfs_combinations'] (list or "auto").

  2. The hot-rolled IS 800 Section 12 lateral frame (OCBF / SCBF / EBF / SMF) -- IS 800:2007 LIMIT STATE:
       lateral_frame_basis = "IS800_LSD"; IS 800 Table 4 combinations (+ IS 1893 6.3 families, 7.8.2 torsion,
       vertical EQ, IS 800 12.2.3 / IS 18168 5.5) generated by the vendored india_combos in the HR pipeline.
       -> load_plan['combinations'] ("auto" or an explicit Table 4 list).

Every capacity slot written by the CFS engine carries `capacity_basis` (IS801_allowable | IS800_LSD | manufacturer_ASD
| nominal | test) and `allowable_increase` (1.0 or 1.3333).  consistency.check FAILs a package where a working-stress
demand meets an LSD capacity (or vice versa), or where 1.333 is applied to a capacity that is not an IS 801 allowable.

No AISI S100 / S240 / S400, ASCE 7 or LRFD combination exists on this branch (D3).
"""
from __future__ import annotations

DESIGN_BASIS = "IS801_WSM"
LATERAL_FRAME_BASIS = "IS800_LSD"
INCREASE_WL_EL = 4.0 / 3.0
IS875_5_CITE = ("IS 875 (Part 5):1987 cl. 8.1: DL; DL+IL; DL+WL; DL+EL; DL+IL+WL; DL+IL+EL (Note 1 snow replaces IL; "
                "Notes 4/5: 0.9 DL against overturning / sliding); Note 2: permissible stresses per the design code (WSM)")
IS801_61_CITE = "IS 801:1975 6.1 F = 0.60 Fy; 6.1.2.1 / 6.1.2.2 stresses 33 1/3 percent greater for wind or earthquake"
CAPACITY_BASES = ("IS801_allowable", "IS800_LSD", "manufacturer_ASD", "nominal", "test", "EOR_input")
WORKING_BASES = ("IS801_allowable", "manufacturer_ASD", "test", "EOR_input")

BASIS_STATEMENT = (
    "Design basis: IS 801:1975 working stress for every cold-formed member (F = 0.60 Fy; IS 875 (Part 5) cl. 8.1 "
    "combinations at factor 1.0; +33 1/3 % allowable only for combinations containing wind or earthquake, IS 801 6.1.2; "
    "effective widths at 0.75 f for those, 5.2.1.1). The lateral force-resisting system is a hot-rolled IS 800:2007 "
    "Section 12 frame designed to IS 800 Table 4 limit-state combinations with IS 1893 (Part 1):2016 forces; cold-formed "
    "members are gravity / wind members only and claim no seismic force-resisting role.")


class BasisError(ValueError):
    pass


def cfs_combinations(plan, cfg=None):
    """IS 875-5 cl. 8.1 working-stress combinations for the CFS members (factor 1.0, 0.9 DL for uplift).
    Each row: {label, fD, fL, fLr, fS, fW, fE, lateral_ref, wind_eq, allowable_increase, eff_width_stress_factor,
    design_basis, cite}.  Wind rows are produced per declared wind case in plan['member_wind'] (pressure patterns
    from india_wind_tables.lowrise_member_wind) or per story-force direction; EL rows are kept for completeness
    (the CFS members carry no lateral-system EQ force -- the hot-rolled frame does)."""
    plan = plan or {}
    sf = plan.get("story_forces") or {}
    has_snow = bool((plan.get("snow_summary") or {}).get("applicable")) or bool((cfg or {}).get("snow"))
    wind_refs = [k for k in sf if k.upper().startswith(("W_", "WX", "WY", "WL"))]
    mw = plan.get("member_wind") or []
    wind_refs += [p.get("name") for p in mw if isinstance(p, dict) and p.get("name")]
    if not wind_refs:
        wind_refs = ["WL"]
    eq_refs = [k for k in sf if k.upper().startswith(("EQ_", "EL"))] or ["EL"]
    rows = []

    def add(label, fD, fL=0.0, fLr=0.0, fS=0.0, fW=0.0, fE=0.0, ref=None, note=""):
        we = bool(fW or fE)
        rows.append({"label": label, "fD": fD, "fL": fL, "fLr": fLr, "fS": fS, "fW": fW, "fE": fE,
                     "lateral_ref": ref, "wind_eq": we, "allowable_increase": INCREASE_WL_EL if we else 1.0,
                     "eff_width_stress_factor": 0.75 if we else 1.0, "design_basis": DESIGN_BASIS,
                     "cite": IS875_5_CITE + (" | " + note if note else "")})

    add("DL", 1.0, note="8.1 (a)")
    add("DL+IL", 1.0, 1.0, 1.0, note="8.1 (b)")
    if has_snow:
        add("DL+SL", 1.0, 0.0, 0.0, 1.0, note="8.1 Note 1: snow replaces imposed load on roofs")
    for w in wind_refs:
        for sg, f in (("+", 1.0), ("-", -1.0)):
            add("DL%s1.0%s" % (sg, w), 1.0, fW=f, ref=w, note="8.1 (c) DL+WL")
            add("DL+IL%s1.0%s" % (sg, w), 1.0, 1.0, 1.0, fW=f, ref=w, note="8.1 (f) DL+IL+WL")
            if has_snow:
                add("DL+SL%s1.0%s" % (sg, w), 1.0, fS=1.0, fW=f, ref=w, note="8.1 (f) with Note 1 snow")
            add("0.9DL%s1.0%s" % (sg, w), 0.9, fW=f, ref=w, note="8.1 Notes 4/5: 0.9 DL, uplift / overturning / sliding")
    for e in eq_refs:
        for sg, f in (("+", 1.0), ("-", -1.0)):
            add("DL%s1.0%s" % (sg, e), 1.0, fE=f, ref=e, note="8.1 (d) DL+EL")
            add("DL+IL%s1.0%s" % (sg, e), 1.0, 1.0, 0.0, fE=f, ref=e,
                note="8.1 (g) DL+IL+EL (IS 875-2 3.2.1 reductions not applied with EL, Note 3)")
            add("0.9DL%s1.0%s" % (sg, e), 0.9, fE=f, ref=e, note="8.1 Notes 4/5: 0.9 DL")
    return rows


def validate_load_plan(cfg) -> list:
    """WP3.1: both labelled families present, bases not mixed.  Returns (sev, msg) findings; ERRORs block."""
    out = []
    say = lambda s, m: out.append((s, m))
    plan = (cfg or {}).get("load_plan")
    if not isinstance(plan, dict):
        say("ERROR", "cfg['load_plan'] missing (LIVE IS 875 / IS 1893 RAG -> load_plan before the pipeline)")
        return out
    if plan.get("design_basis") != DESIGN_BASIS:
        say("ERROR", "load_plan.design_basis must be %r (IS 801 working stress, decision D5); got %r"
            % (DESIGN_BASIS, plan.get("design_basis")))
    if plan.get("lateral_frame_basis") not in (LATERAL_FRAME_BASIS,) and not (cfg or {}).get("all_cfs_portal"):
        say("ERROR", "load_plan.lateral_frame_basis must be %r (hot-rolled IS 800 Section 12 frame, decision D3); got %r"
            % (LATERAL_FRAME_BASIS, plan.get("lateral_frame_basis")))
    for k in ("lrfd", "asce", "aisi"):
        if any(k in str(x).lower() for x in plan.keys()):
            say("ERROR", "load_plan carries a %s key -- no US load basis on this branch (D3)" % k.upper())
    cc = plan.get("cfs_combinations")
    if cc == "auto":
        cc = cfs_combinations(plan, cfg)
    if not isinstance(cc, list) or not cc:
        say("ERROR", "load_plan.cfs_combinations missing: the IS 875-5 8.1 working-stress set for the CFS members "
                     "(write 'auto' to generate it from india_cfs_basis.cfs_combinations)")
    else:
        for i, c in enumerate(cc):
            if not isinstance(c, dict):
                say("ERROR", "cfs_combinations[%d] must be an object" % i); continue
            if c.get("design_basis") not in (None, DESIGN_BASIS):
                say("ERROR", "cfs_combinations[%d] (%s) design_basis %r != IS801_WSM (mixed bases)" % (i, c.get("label"), c.get("design_basis")))
            for key in ("fD", "fL", "fLr", "fS", "fW", "fE"):
                v = c.get(key)
                if v is None:
                    continue
                av = abs(float(v))
                ok = (av in (0.0, 1.0)) or (key == "fD" and av == 0.9)
                if not ok:
                    say("ERROR", "cfs_combinations[%d] (%s): %s = %s is a partial factor -- IS 801 is working stress; IS 875-5 "
                                 "8.1 combinations are at 1.0 (0.9 DL for uplift). Factored loads against 0.6 Fy compound "
                                 "to 2.5 on yield (CFSREPO-01)" % (i, c.get("label"), key, v))
            we = bool(c.get("fW") or c.get("fE"))
            inc = c.get("allowable_increase")
            if inc is not None and abs(float(inc) - (INCREASE_WL_EL if we else 1.0)) > 1e-6:
                say("ERROR", "cfs_combinations[%d] (%s): allowable_increase %s but IS 801 6.1.2 gives %s for this combination"
                    % (i, c.get("label"), inc, INCREASE_WL_EL if we else 1.0))
    hc = plan.get("combinations")
    if not (cfg or {}).get("all_cfs_portal"):
        if hc != "auto" and not (isinstance(hc, list) and hc):
            say("ERROR", "load_plan.combinations (IS 800 Table 4 set for the hot-rolled lateral frame) missing -- write "
                         "'auto' (india_combos.expand_combinations in the HR pipeline)")
        elif isinstance(hc, list):
            for i, c in enumerate(hc):
                if isinstance(c, dict) and c.get("design_basis") not in (None, LATERAL_FRAME_BASIS):
                    say("ERROR", "combinations[%d] (%s) design_basis %r on the IS 800 frame set (mixed bases)"
                        % (i, c.get("label"), c.get("design_basis")))
    if plan.get("story_forces") and str(plan.get("story_forces_units") or "").lower() not in ("n", "kn"):
        say("ERROR", "load_plan.story_forces present without story_forces_units ('N' or 'kN') (WP1.12)")
    return out


def capacity_slot(capacity, basis="IS801_allowable", wind_eq=False, clause=None, cite=None, units=None):
    """A capacity record every package slot must carry (WP3.1)."""
    if basis not in CAPACITY_BASES:
        raise BasisError("capacity_basis %r not in %s" % (basis, CAPACITY_BASES))
    inc = INCREASE_WL_EL if (wind_eq and basis == "IS801_allowable") else 1.0
    return {"capacity": capacity, "capacity_basis": basis, "allowable_increase": inc, "clause": clause, "cite": cite,
            "units": units}


def basis_issues(pkg) -> list:
    """consistency rule: every slot with a capacity carries capacity_basis + allowable_increase; the demand level of the
    slot (working | LSD) matches the capacity basis; 1.333 only on IS801_allowable."""
    issues = []

    def walk(obj, path):
        if isinstance(obj, dict):
            cap = obj.get("capacity")
            if cap is not None and not isinstance(cap, str):
                cb = obj.get("capacity_basis") or (cap.get("capacity_basis") if isinstance(cap, dict) else None)
                inc = obj.get("allowable_increase", (cap.get("allowable_increase") if isinstance(cap, dict) else None))
                lvl = obj.get("demand_level") or "working"
                if cb is None:
                    issues.append("%s: capacity without capacity_basis (WP3.1)" % path)
                elif cb not in CAPACITY_BASES:
                    issues.append("%s: capacity_basis %r unknown" % (path, cb))
                elif lvl == "working" and cb == "IS800_LSD":
                    issues.append("%s: working-stress demand against an IS 800 LSD capacity (mixed bases)" % path)
                elif lvl == "LSD" and cb in WORKING_BASES:
                    issues.append("%s: LSD (factored) demand against a working-stress capacity (mixed bases)" % path)
                if inc is not None and abs(float(inc) - 1.0) > 1e-6 and cb != "IS801_allowable":
                    issues.append("%s: allowable_increase %s applied to a %s capacity (only IS 801 allowables take 6.1.2)"
                                  % (path, inc, cb))
            for k, v in obj.items():
                if k not in ("capacity",):
                    walk(v, path + "." + str(k))
        elif isinstance(obj, list):
            for i, v in enumerate(obj):
                walk(v, "%s[%d]" % (path, i))
    walk(pkg, "pkg")
    return issues
